import type { MemoryModel } from './types.js';
import type { Capability } from './analysis/capabilities.js';
import type { DiscoveredJourney } from './analysis/journeys.js';
import type { AgentContext } from './agent-mode.js';
import { explainRepository } from './explain.js';
import { computeAiReadiness } from './ai-readiness.js';
import { SUPPORTED_LANGUAGE_COUNT } from './languages/index.js';
import {
  buildLanguagePipelineMermaid,
  buildExtractorRoutingMermaid,
  buildLanguageFamiliesMermaid,
  buildRepositoryLanguagePieMermaid,
} from './languages/docs.js';
import { buildDomainGraphMermaid } from './graph/mermaid.js';
import { buildAgentDisciplineRules, buildDisciplineSkillSection } from './discipline/agent-discipline.js';

export interface AiToolkit {
  agentsMd: string;
  cursorRule: string;
  aiPrompt: string;
  claudeProjectInstructions: string;
  suggestedPrompts: string[];
  contextFiles: string[];
}

export function buildSuggestedPrompts(memory: MemoryModel): string[] {
  const caps = (memory.capabilities ?? []).slice(0, 3).map((c) => c.signature.name);
  const prompts = [
    'Explain this codebase in plain language — architecture, capabilities, and where to start.',
    'Where does authentication start? Show me the entry route and handler files.',
    'What breaks if I change the most central service? List dependents and blast radius.',
    'List all business capabilities — not folder names, actual product features.',
    'Show me the critical paths and highest-risk domains before I ship.',
    'I need to add a new feature — which domain and services should I touch?',
    'What are the architecture smells and how do I fix them?',
    'Generate a safe refactor plan for the highest-coupling domain.',
  ];

  if (caps.length > 0) {
    prompts.push(`How does ${caps[0]} work end-to-end?`);
  }
  if (memory.journeys && memory.journeys.length > 0) {
    prompts.push(`Walk me through the ${memory.journeys[0]!.signature.name} user journey.`);
  }
  if (memory.flows.length > 0) {
    prompts.push(`Trace the ${memory.flows[0]!.name} flow step by step.`);
  }

  return prompts.slice(0, 12);
}

export function buildContextFiles(memory: MemoryModel): string[] {
  const files = new Set<string>([
    '.mnemos/project.dna.json',
    '.mnemos/agent_context.json',
    '.mnemos/context/architecture.md',
    '.mnemos/context/languages.md',
    '.mnemos/context/README.md',
    '.mnemos/context/graphs.md',
    '.mnemos/context/flows.md',
    '.mnemos/context/domains.md',
  ]);

  for (const d of memory.domains.slice(0, 5)) {
    for (const ep of d.entryPoints.slice(0, 2)) {
      if (ep) files.add(ep);
    }
  }

  for (const cp of memory.criticalPaths.slice(0, 3)) {
    for (const n of cp.nodes.slice(0, 2)) {
      if (typeof n === 'string' && n.includes('/')) files.add(n);
    }
  }

  return [...files].slice(0, 16);
}

export function buildAgentsMd(
  memory: MemoryModel,
  capabilities: Capability[],
  journeys: DiscoveredJourney[],
): string {
  const explain = explainRepository(memory);
  const ai = computeAiReadiness(memory);
  const caps = capabilities.slice(0, 8);
  const jrn = journeys.slice(0, 6);
  const domains = memory.domains
    .filter((d) => !/^(test|tests|examples?|acceptance)$/i.test(d.name))
    .slice(0, 10);

  const lines = [
    `# ${memory.repository} — Agent Guide`,
    '',
    '> Generated by [Mnemos](https://github.com/mnemos). Read this before exploring source files.',
    '',
    '## Quick Start for AI Agents',
    '',
    '1. Read `.mnemos/project.dna.json` first — compressed repository DNA (~few thousand tokens).',
    '2. Use `.mnemos/agent_context.json` for capabilities, domains, journeys, and search hints.',
    '3. Ask impact questions before editing central services — check dependents in DNA or run `mnemos ask "what breaks if X changes?"`.',
    '4. Prefer domain entry points listed below over random file grepping.',
    '',
    `## One-Liner`,
    '',
    explain.oneLiner,
    '',
    `## Architecture`,
    '',
    `- **Type:** ${memory.architecture.type}`,
    `- **Layers:** ${memory.architecture.layers.join(' → ') || 'not detected'}`,
    `- **Health score:** ${explain.memoryScore}/100`,
    `- **AI readiness:** ${ai.score}/100`,
    '',
    memory.architecture.summary,
    '',
    `## Language Support`,
    '',
    `Mnemos analyzed this repo with **${SUPPORTED_LANGUAGE_COUNT}** supported languages engine-wide.`,
    `Detected here: ${Object.keys(memory.architecture.languages ?? {}).length} language(s), ${Object.values(memory.architecture.languages ?? {}).reduce((s, n) => s + n, 0).toLocaleString()} source files.`,
    '',
    'Read `.mnemos/context/README.md` for the full diagram index.',
    'Read `.mnemos/context/languages.md` for file distribution charts and the parsing pipeline graph.',
    'Read `.mnemos/context/graphs.md` for domain, flow, dependency, and risk Mermaid diagrams.',
    '',
    buildDomainGraphMermaid(memory),
    '',
    '### Language distribution (this repo)',
    '',
    buildRepositoryLanguagePieMermaid(memory.architecture.languages ?? {}),
    '',
    '### Extractor routing',
    '',
    buildExtractorRoutingMermaid(),
    '',
    '### Parsing pipeline',
    '',
    buildLanguagePipelineMermaid(),
    '',
    '### Language families (engine coverage)',
    '',
    buildLanguageFamiliesMermaid(),
    '',
  ];

  if (caps.length > 0) {
    lines.push('## Capabilities', '');
    for (const c of caps) {
      lines.push(`- **${c.signature.name}** — ${c.signature.purpose}`);
      if (c.services.length > 0) {
        lines.push(`  - Services: ${c.services.slice(0, 4).join(', ')}`);
      }
    }
    lines.push('');
  }

  if (jrn.length > 0) {
    lines.push('## User Journeys', '');
    for (const j of jrn) {
      lines.push(`- **${j.signature.name}** — entry: \`${j.entryRoute ?? j.entryPoint}\``);
    }
    lines.push('');
  }

  if (domains.length > 0) {
    lines.push('## Domains (start here)', '');
    for (const d of domains) {
      const eps = d.entryPoints.slice(0, 3).map((e) => `\`${e}\``).join(', ');
      lines.push(`- **${d.name}** — ${d.description || 'core domain'}${eps ? ` · ${eps}` : ''}`);
    }
    lines.push('');
  }

  if (memory.criticalPaths.length > 0) {
    lines.push('## Critical Paths (edit carefully)', '');
    for (const cp of memory.criticalPaths.slice(0, 5)) {
      lines.push(`- **${cp.name}** (${cp.risk} risk) — ${cp.description}`);
    }
    lines.push('');
  }

  lines.push(
    '## Coding Conventions',
    '',
    '- Match existing domain boundaries — do not create cross-domain coupling.',
    '- Run `mnemos build --watch` to keep memory fresh while vibe-coding.',
    '- Run `mnemos review <diff>` before opening a PR to catch blast-radius issues.',
    '- Point Cursor/Claude at `.mnemos/project.dna.json` via @-mention or project rules.',
    '',
    ...buildAgentDisciplineRules(),
    '## Mnemos Commands',
    '',
    '```bash',
    'npx mnemos .              # analyze + generate DNA',
    'mnemos ask "question"     # architecture copilot',
    'mnemos serve              # localhost:4000 for agent queries',
    'mnemos build --watch      # auto-rebuild on save',
    '```',
    '',
  );

  return lines.join('\n');
}

export function buildCursorRule(memory: MemoryModel, context: AgentContext): string {
  const caps = context.capabilities.slice(0, 6).map((c) => c.name).join(', ');
  const domains = context.domains.slice(0, 6).map((d) => d.name).join(', ');
  const files = buildContextFiles(memory).slice(0, 8).join(', ');

  return `---
description: Repository architecture from Mnemos — read DNA before coding
globs:
alwaysApply: true
---

# ${memory.repository} — Mnemos Architecture Memory

Before reading source files or making changes, load repository context from Mnemos:

1. **Read first:** \`.mnemos/project.dna.json\` and \`.mnemos/agent_context.json\`
2. **Languages:** \`.mnemos/context/languages.md\` — stack charts + ${SUPPORTED_LANGUAGE_COUNT}-language parsing pipeline
3. **Graphs:** \`.mnemos/context/graphs.md\` — domain, flow, dependency, and risk Mermaid diagrams
4. **Architecture:** ${memory.architecture.type} — ${memory.architecture.summary.slice(0, 200)}
5. **Capabilities:** ${caps || 'see DNA'}
6. **Domains:** ${domains || 'see DNA'}
7. **Key files:** ${files}

## Rules for AI-assisted coding

- Use Mnemos DNA as ground truth for architecture — do not guess folder structure
- Before editing a service, check dependents via \`mnemos ask "what breaks if [service] changes?"\`
- Prefer domain entry points over scanning the whole repo
- Keep changes within the relevant capability/domain boundary
- After significant edits, suggest running \`mnemos build\` to refresh memory

${buildAgentDisciplineRules().join('\n')}

## Vibe-coder prompts that work well

${buildSuggestedPrompts(memory)
  .slice(0, 6)
  .map((p) => `- "${p}"`)
  .join('\n')}

## Local memory server

Run \`mnemos serve\` for live queries at http://localhost:4000/dna and /copilot?q=
`;
}

export function buildAiPrompt(memory: MemoryModel, context: AgentContext): string {
  const explain = explainRepository(memory);
  const caps = context.capabilities.slice(0, 8);
  const journeys = context.journeys.slice(0, 5);

  const lines = [
    `You are helping me work on **${memory.repository}**. I have a Mnemos memory layer — use it as ground truth.`,
    '',
    '## Repository DNA (read @.mnemos/project.dna.json)',
    '',
    explain.oneLiner,
    '',
    `Architecture: ${memory.architecture.type}`,
    `Health: ${explain.memoryScore}/100`,
    '',
    '### Capabilities',
    ...caps.map((c) => `- ${c.name}: ${c.purpose}`),
    '',
  ];

  if (journeys.length > 0) {
    lines.push('### User Journeys', ...journeys.map((j) => `- ${j.name} → ${j.entry}`), '');
  }

  lines.push(
    '### Instructions',
    '- Answer using Mnemos context before grepping the whole repo',
    '- Cite specific files and domains when suggesting changes',
    '- Warn me about blast radius on central services',
    '- Keep suggestions aligned with existing domain boundaries',
    '',
    ...buildAgentDisciplineRules().slice(2),
    'My question:',
  );

  return lines.join('\n');
}

export function buildClaudeProjectInstructions(memory: MemoryModel, context: AgentContext): string {
  return `# ${memory.repository} — Claude Project Instructions

Add these files to your Claude Project knowledge:
- \`.mnemos/project.dna.json\`
- \`.mnemos/agent_context.json\`
- \`.mnemos/context/architecture.md\`
- \`.mnemos/context/languages.md\`

${context.summary}

Top capabilities: ${context.mental_model.top_capabilities.join(', ')}
Central domains: ${context.mental_model.central_domains.join(', ')}

When I ask architecture questions, answer from Mnemos DNA first.
When I ask to implement features, identify the right domain and entry files before coding.

${buildDisciplineSkillSection()}
`;
}

export function buildAiToolkit(
  memory: MemoryModel,
  capabilities: Capability[],
  journeys: DiscoveredJourney[],
  context: AgentContext,
): AiToolkit {
  return {
    agentsMd: buildAgentsMd(memory, capabilities, journeys),
    cursorRule: buildCursorRule(memory, context),
    aiPrompt: buildAiPrompt(memory, context),
    claudeProjectInstructions: buildClaudeProjectInstructions(memory, context),
    suggestedPrompts: buildSuggestedPrompts(memory),
    contextFiles: buildContextFiles(memory),
  };
}

const MNEMOS_MARKER_START = '<!-- mnemos:start -->';
const MNEMOS_MARKER_END = '<!-- mnemos:end -->';

export function buildSkillMd(memory: MemoryModel, context: AgentContext): string {
  const caps = context.capabilities.slice(0, 6).map((c) => c.name).join(', ');
  const domains = context.domains.slice(0, 6).map((d) => d.name).join(', ');
  const files = buildContextFiles(memory).slice(0, 8).map((f) => `\`${f}\``).join(', ');

  return `# Mnemos Architecture Skill

Use Mnemos repository memory as ground truth before reading source files.

## Context files (read first)

${files}

## Architecture

- **Repository:** ${memory.repository}
- **Type:** ${memory.architecture.type}
- **Summary:** ${memory.architecture.summary.slice(0, 300)}
- **Capabilities:** ${caps || 'see DNA'}
- **Domains:** ${domains || 'see DNA'}

## Rules

- Read \`.mnemos/project.dna.json\` and \`.mnemos/agent_context.json\` before exploring code
- Check blast radius before editing central services: \`mnemos ask "what breaks if [service] changes?"\`
- Prefer domain entry points over whole-repo grepping
- Run \`mnemos build\` after significant architectural changes

${buildAgentDisciplineRules().join('\n')}

## Starter prompts

${buildSuggestedPrompts(memory)
  .slice(0, 6)
  .map((p) => `- ${p}`)
  .join('\n')}
`;
}

export function buildSteeringMd(memory: MemoryModel, context: AgentContext): string {
  return `# Mnemos Steering — ${memory.repository}

${context.summary}

**Architecture:** ${memory.architecture.type}
**Top capabilities:** ${context.mental_model.top_capabilities.join(', ')}
**Central domains:** ${context.mental_model.central_domains.join(', ')}

Always consult Mnemos DNA (\`.mnemos/project.dna.json\`) before making architectural decisions.
`;
}

export function buildVscodeInstructions(memory: MemoryModel, context: AgentContext): string {
  return buildSkillMd(memory, context).replace(
    '# Mnemos Architecture Skill',
    '# Mnemos — VS Code Copilot Instructions',
  );
}

export function buildCopilotInstructions(memory: MemoryModel, context: AgentContext): string {
  return `# GitHub Copilot Instructions — ${memory.repository}

${buildSkillMd(memory, context)}

## Copilot-specific

- Reference \`.mnemos/project.dna.json\` when answering architecture questions
- Suggest \`mnemos review\` before large refactors
- Keep changes within detected domain boundaries
`;
}

export function buildWindsurfRule(memory: MemoryModel, context: AgentContext): string {
  return buildCursorRule(memory, context).replace(/^---[\s\S]*?---\n\n/, '');
}

export function buildGeminiMd(memory: MemoryModel, context: AgentContext): string {
  return `# ${memory.repository} — Gemini Project Context

${MNEMOS_MARKER_START}
${buildClaudeProjectInstructions(memory, context)}
${MNEMOS_MARKER_END}
`;
}

export function buildClaudeMdSection(memory: MemoryModel, context: AgentContext): string {
  return `\n${MNEMOS_MARKER_START}\n${buildClaudeProjectInstructions(memory, context)}\n${MNEMOS_MARKER_END}\n`;
}

export function stripMnemosSection(content: string): string {
  const start = content.indexOf(MNEMOS_MARKER_START);
  if (start === -1) return content;
  const end = content.indexOf(MNEMOS_MARKER_END, start);
  if (end === -1) return content.slice(0, start).trimEnd();
  return (content.slice(0, start) + content.slice(end + MNEMOS_MARKER_END.length)).trimEnd();
}
