import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { MemoryModel } from './types.js';
import { computeMemoryScore } from './report.js';
import { buildAgentExports } from './agent-mode.js';
import { computeAiReadiness } from './ai-readiness.js';

export interface SnapshotResult {
  outputDir: string;
  files: string[];
}

export async function generateSnapshots(
  memory: MemoryModel,
  outputDir: string,
): Promise<SnapshotResult> {
  const snapDir = path.join(outputDir, 'snapshots');
  await mkdir(snapDir, { recursive: true });

  const memoryScore = computeMemoryScore(memory);
  const aiReadiness = computeAiReadiness(memory);
  const capabilities = memory.capabilities ?? [];
  const journeys = memory.journeys ?? [];
  const exports = buildAgentExports({
    memory,
    capabilities,
    journeys,
    memoryScore: memoryScore.overall,
  });

  const files: Record<string, string> = {
    'dna-summary.svg': renderDnaSummary(memory, exports.dna, memoryScore, aiReadiness),
    'capabilities.svg': renderCapabilitiesCard(capabilities.slice(0, 6)),
    'journeys.svg': renderJourneysCard(journeys.slice(0, 4)),
    'health-score.svg': renderHealthCard(memoryScore, aiReadiness),
    'architecture.svg': renderArchitectureCard(memory),
    'ai-context.svg': renderAiContextCard(memory, aiReadiness, exports.dna),
    'journey-flow.svg': renderJourneyFlowCard(journeys.slice(0, 1)),
    'terminal-build.svg': renderTerminalBuildCard(memory, memoryScore, aiReadiness),
    'benchmark-results.svg': renderBenchmarkResultsCard(memory),
  };

  const written: string[] = [];
  for (const [name, content] of Object.entries(files)) {
    const filePath = path.join(snapDir, name);
    await writeFile(filePath, content, 'utf-8');
    written.push(filePath);
  }

  return { outputDir: snapDir, files: written };
}

function renderDnaSummary(
  memory: MemoryModel,
  dna: ReturnType<typeof buildAgentExports>['dna'],
  score: ReturnType<typeof computeMemoryScore>,
  aiReadiness: ReturnType<typeof computeAiReadiness>,
): string {
  const caps = dna.capabilities.slice(0, 4).map((c) => c.name);
  return svgWrap(800, 480, `
    <rect width="800" height="480" rx="24" fill="#fbfbfd"/>
    <rect x="1" y="1" width="798" height="478" rx="23" fill="none" stroke="#e8e8ed" stroke-width="2"/>
    <text x="40" y="56" font-family="system-ui,sans-serif" font-size="13" fill="#5e5ce6" font-weight="600" letter-spacing="1">REPOSITORY DNA</text>
    <text x="40" y="100" font-family="Georgia,serif" font-size="36" fill="#1d1d1f" font-weight="600">${esc(memory.repository)}</text>
    <text x="40" y="140" font-family="system-ui,sans-serif" font-size="16" fill="#515154">${esc(dna.one_liner)}</text>
    ${caps.map((c, i) => `
      <rect x="40" y="${180 + i * 44}" width="360" height="36" rx="10" fill="#ffffff" stroke="#e8e8ed"/>
      <circle cx="58" cy="${198 + i * 44}" r="4" fill="#5e5ce6"/>
      <text x="72" y="${203 + i * 44}" font-family="system-ui,sans-serif" font-size="14" fill="#1d1d1f" dominant-baseline="middle">${esc(c)}</text>
    `).join('')}
    <rect x="440" y="160" width="320" height="280" rx="16" fill="#ffffff" stroke="#e8e8ed"/>
    <text x="460" y="200" font-family="system-ui,sans-serif" font-size="12" fill="#86868b" font-weight="600">HEALTH SCORE</text>
    <text x="460" y="250" font-family="system-ui,sans-serif" font-size="56" fill="#1d1d1f" font-weight="700">${score.overall}</text>
    <text x="530" y="250" font-family="system-ui,sans-serif" font-size="20" fill="#86868b">/100</text>
    <text x="460" y="290" font-family="system-ui,sans-serif" font-size="12" fill="#86868b" font-weight="600">AI READINESS</text>
    <text x="460" y="330" font-family="system-ui,sans-serif" font-size="40" fill="#30d158" font-weight="700">${aiReadiness.score}</text>
    <text x="520" y="330" font-family="system-ui,sans-serif" font-size="18" fill="#86868b">/100</text>
    <text x="460" y="380" font-family="system-ui,sans-serif" font-size="13" fill="#515154">${memory.domains.length} domains · ${memory.flows.length} flows · ${memory.apis.length} APIs</text>
    <text x="460" y="410" font-family="system-ui,sans-serif" font-size="13" fill="#515154">${dna.architecture.type} · ${memory.stats.filesScanned} files</text>
    <text x="40" y="450" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Generated by Mnemos · project.dna.json</text>
  `);
}

function renderCapabilitiesCard(
  capabilities: NonNullable<MemoryModel['capabilities']>,
): string {
  if (capabilities.length === 0) {
    return svgWrap(800, 200, `
      <rect width="800" height="200" rx="24" fill="#f5f5f7"/>
      <text x="40" y="80" font-family="system-ui,sans-serif" font-size="16" fill="#86868b">No capabilities detected yet</text>
    `);
  }

  const items = capabilities;
  return svgWrap(800, 420, `
    <rect width="800" height="420" rx="24" fill="#f5f5f7"/>
    <text x="40" y="50" font-family="system-ui,sans-serif" font-size="13" fill="#5e5ce6" font-weight="600" letter-spacing="1">CAPABILITIES</text>
    <text x="40" y="88" font-family="Georgia,serif" font-size="28" fill="#1d1d1f" font-weight="600">What this software does</text>
    ${items.map((c, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = 40 + col * 370;
      const y = 110 + row * 140;
      return `
        <rect x="${x}" y="${y}" width="350" height="120" rx="14" fill="#ffffff" stroke="#e8e8ed"/>
        <text x="${x + 20}" y="${y + 32}" font-family="system-ui,sans-serif" font-size="11" fill="#86868b" font-weight="600">${esc(c.signature.category.toUpperCase())}</text>
        <text x="${x + 20}" y="${y + 58}" font-family="system-ui,sans-serif" font-size="17" fill="#1d1d1f" font-weight="600">${esc(c.signature.name)}</text>
        <text x="${x + 20}" y="${y + 82}" font-family="system-ui,sans-serif" font-size="13" fill="#515154">${esc(truncate(c.signature.purpose, 48))}</text>
        <text x="${x + 20}" y="${y + 104}" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">${c.services.length} services · ${c.apis.length} APIs</text>
      `;
    }).join('')}
    <text x="40" y="400" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Mnemos Capability Map</text>
  `);
}

function renderJourneysCard(
  journeys: NonNullable<MemoryModel['journeys']>,
): string {
  const items = journeys.length > 0 ? journeys : [];
  const journeyBlocks = items.map((j, i) => {
    const y = 100 + i * 72;
    const steps = j.steps.slice(0, 5).map((s) => s.name);
    const flow = steps.join(' → ');
    return `
      <text x="40" y="${y}" font-family="system-ui,sans-serif" font-size="16" fill="#1d1d1f" font-weight="600">${esc(j.signature.name)}</text>
      <text x="40" y="${y + 22}" font-family="system-ui,sans-serif" font-size="13" fill="#515154">${esc(truncate(flow, 90))}</text>
      ${i < items.length - 1 ? `<line x1="40" y1="${y + 38}" x2="760" y2="${y + 38}" stroke="#e8e8ed"/>` : ''}
    `;
  }).join('');

  return svgWrap(800, Math.max(320, 120 + items.length * 72), `
    <rect width="800" height="${Math.max(320, 120 + items.length * 72)}" rx="24" fill="#fbfbfd"/>
    <text x="40" y="50" font-family="system-ui,sans-serif" font-size="13" fill="#5e5ce6" font-weight="600" letter-spacing="1">USER JOURNEYS</text>
    <text x="40" y="82" font-family="Georgia,serif" font-size="24" fill="#1d1d1f" font-weight="600">How users move through the product</text>
    ${journeyBlocks || '<text x="40" y="140" font-family="system-ui,sans-serif" font-size="14" fill="#86868b">No journeys discovered yet</text>'}
    <text x="40" y="${Math.max(300, 100 + items.length * 72)}" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Mnemos Journey Map</text>
  `);
}

function renderHealthCard(
  score: ReturnType<typeof computeMemoryScore>,
  aiReadiness: ReturnType<typeof computeAiReadiness>,
): string {
  const metrics = [
    { label: 'Architecture', value: score.architectureClarity },
    { label: 'Maintainability', value: score.coupling },
    { label: 'Complexity', value: Math.max(0, 100 - score.dependencyComplexity) },
    { label: 'Documentation', value: score.documentationQuality },
    { label: 'Coupling', value: score.coupling },
    { label: 'AI Readiness', value: aiReadiness.score },
  ];

  return svgWrap(800, 400, `
    <rect width="800" height="400" rx="24" fill="#1d1d1f"/>
    <text x="40" y="50" font-family="system-ui,sans-serif" font-size="13" fill="#5e5ce6" font-weight="600" letter-spacing="1">REPOSITORY HEALTH</text>
    <text x="40" y="110" font-family="system-ui,sans-serif" font-size="72" fill="#ffffff" font-weight="700">${score.overall}</text>
    <text x="140" y="110" font-family="system-ui,sans-serif" font-size="28" fill="#86868b">/100</text>
    ${metrics.map((m, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 40 + col * 240;
      const y = 160 + row * 100;
      return `
        <text x="${x}" y="${y}" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">${m.label}</text>
        <text x="${x}" y="${y + 32}" font-family="system-ui,sans-serif" font-size="32" fill="#ffffff" font-weight="600">${m.value}</text>
        <rect x="${x}" y="${y + 44}" width="200" height="4" rx="2" fill="#333"/>
        <rect x="${x}" y="${y + 44}" width="${m.value * 2}" height="4" rx="2" fill="#5e5ce6"/>
      `;
    }).join('')}
    <text x="40" y="380" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Mnemos Health Score</text>
  `);
}

function renderArchitectureCard(memory: MemoryModel): string {
  const domains = memory.domains.slice(0, 6);
  return svgWrap(800, 360, `
    <rect width="800" height="360" rx="24" fill="#ffffff" stroke="#e8e8ed" stroke-width="2"/>
    <text x="40" y="50" font-family="system-ui,sans-serif" font-size="13" fill="#0a84ff" font-weight="600" letter-spacing="1">ARCHITECTURE</text>
    <text x="40" y="88" font-family="Georgia,serif" font-size="28" fill="#1d1d1f" font-weight="600">${esc(memory.architecture.type)}</text>
    <text x="40" y="118" font-family="system-ui,sans-serif" font-size="14" fill="#515154">${esc(truncate(memory.architecture.summary, 80))}</text>
    ${domains.map((d, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const x = 40 + col * 240;
      const y = 150 + row * 90;
      const services = memory.services.filter((s) => s.domain === d.id || s.domain === d.name).length;
      return `
        <rect x="${x}" y="${y}" width="220" height="72" rx="12" fill="#f5f5f7"/>
        <text x="${x + 16}" y="${y + 28}" font-family="system-ui,sans-serif" font-size="15" fill="#1d1d1f" font-weight="600">${esc(d.name)}</text>
        <text x="${x + 16}" y="${y + 50}" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">${d.nodes.length} nodes · ${services} services</text>
      `;
    }).join('')}
    <text x="40" y="340" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Mnemos Architecture Canvas</text>
  `);
}

function svgWrap(width: number, height: number, body: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
${body}
</svg>`;
}

function renderAiContextCard(
  memory: MemoryModel,
  aiReadiness: ReturnType<typeof computeAiReadiness>,
  dna: ReturnType<typeof buildAgentExports>['dna'],
): string {
  const topDomains = dna.domains.slice(0, 6);
  const criticalCount = dna.critical_paths.filter((p) => p.risk === 'high').length;
  const riskCount = dna.risks.length;

  const tiles = [
    { label: 'Capabilities', value: dna.capabilities.length, color: '#5e5ce6' },
    { label: 'Domains', value: dna.key_metrics.domains, color: '#0a84ff' },
    { label: 'Critical Paths', value: criticalCount, color: '#ff9f0a' },
    { label: 'AI Readiness', value: aiReadiness.score, color: '#30d158' },
  ];

  return svgWrap(800, 460, `
    <defs>
      <linearGradient id="aiGrad" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0%" stop-color="#5e5ce6"/>
        <stop offset="100%" stop-color="#0a84ff"/>
      </linearGradient>
    </defs>
    <rect width="800" height="460" rx="24" fill="#0b0b10"/>
    <rect x="1" y="1" width="798" height="458" rx="23" fill="none" stroke="#1f1f25" stroke-width="2"/>
    <rect x="0" y="0" width="800" height="180" rx="24" fill="url(#aiGrad)" opacity="0.16"/>
    <text x="40" y="56" font-family="system-ui,sans-serif" font-size="13" fill="#a5a3ff" font-weight="600" letter-spacing="2">AI CONTEXT VIEW</text>
    <text x="40" y="100" font-family="Georgia,serif" font-size="34" fill="#ffffff" font-weight="600">Repository DNA</text>
    <text x="40" y="138" font-family="system-ui,sans-serif" font-size="15" fill="#a1a1aa">${esc(memory.repository)} · ${esc(memory.architecture.type)}</text>

    ${tiles
      .map((t, i) => {
        const col = i % 4;
        const x = 40 + col * 180;
        const y = 200;
        return `
        <rect x="${x}" y="${y}" width="160" height="120" rx="14" fill="#15151b" stroke="#26262e"/>
        <text x="${x + 16}" y="${y + 30}" font-family="system-ui,sans-serif" font-size="11" fill="#71717a" font-weight="600" letter-spacing="1">${t.label.toUpperCase()}</text>
        <text x="${x + 16}" y="${y + 78}" font-family="system-ui,sans-serif" font-size="42" fill="${t.color}" font-weight="700">${t.value}</text>
      `;
      })
      .join('')}

    <text x="40" y="350" font-family="system-ui,sans-serif" font-size="12" fill="#71717a" font-weight="600" letter-spacing="1">TOP DOMAINS</text>
    ${topDomains
      .slice(0, 4)
      .map((d, i) => {
        const col = i % 2;
        const row = Math.floor(i / 2);
        const x = 40 + col * 360;
        const y = 370 + row * 36;
        return `
        <circle cx="${x + 8}" cy="${y + 8}" r="4" fill="#5e5ce6"/>
        <text x="${x + 22}" y="${y + 13}" font-family="system-ui,sans-serif" font-size="14" fill="#e4e4e7" font-weight="500">${esc(d.name)}</text>
        <text x="${x + 360 - 70}" y="${y + 13}" font-family="system-ui,sans-serif" font-size="12" fill="#71717a" text-anchor="end">${d.services} services</text>
      `;
      })
      .join('')}

    <rect x="40" y="430" width="720" height="1" fill="#26262e"/>
    <text x="40" y="448" font-family="system-ui,sans-serif" font-size="11" fill="#52525b">Drop project.dna.json into Claude, Cursor, or Codex for instant understanding.</text>
  `);
}

function renderJourneyFlowCard(
  journeys: NonNullable<MemoryModel['journeys']>,
): string {
  if (journeys.length === 0) {
    return svgWrap(800, 240, `
      <rect width="800" height="240" rx="24" fill="#fbfbfd" stroke="#e8e8ed"/>
      <text x="40" y="60" font-family="system-ui,sans-serif" font-size="13" fill="#5e5ce6" font-weight="600" letter-spacing="1">JOURNEY VIEW</text>
      <text x="40" y="110" font-family="system-ui,sans-serif" font-size="18" fill="#86868b">No user journeys discovered yet</text>
    `);
  }

  const journey = journeys[0];
  const steps = journey.steps.slice(0, 5);
  const stepWidth = 700 / Math.max(1, steps.length);
  const yMid = 180;

  const stepNodes = steps
    .map((step, i) => {
      const x = 50 + i * stepWidth;
      return `
        <circle cx="${x + stepWidth / 2}" cy="${yMid}" r="34" fill="#ffffff" stroke="#5e5ce6" stroke-width="2"/>
        <text x="${x + stepWidth / 2}" y="${yMid + 5}" font-family="system-ui,sans-serif" font-size="11" fill="#5e5ce6" font-weight="600" text-anchor="middle">${i + 1}</text>
        <text x="${x + stepWidth / 2}" y="${yMid + 64}" font-family="system-ui,sans-serif" font-size="12" fill="#1d1d1f" text-anchor="middle" font-weight="600">${esc(truncate(step.name, 14))}</text>
        ${
          i < steps.length - 1
            ? `<line x1="${x + stepWidth / 2 + 36}" y1="${yMid}" x2="${x + stepWidth + stepWidth / 2 - 36}" y2="${yMid}" stroke="#c7c7cc" stroke-width="2" stroke-dasharray="4 4"/>`
            : ''
        }
      `;
    })
    .join('');

  return svgWrap(800, 320, `
    <rect width="800" height="320" rx="24" fill="#fbfbfd" stroke="#e8e8ed" stroke-width="2"/>
    <text x="40" y="56" font-family="system-ui,sans-serif" font-size="13" fill="#5e5ce6" font-weight="600" letter-spacing="1">JOURNEY VIEW</text>
    <text x="40" y="100" font-family="Georgia,serif" font-size="28" fill="#1d1d1f" font-weight="600">${esc(journey.signature.name)}</text>
    <text x="40" y="130" font-family="system-ui,sans-serif" font-size="14" fill="#515154">${esc(truncate(journey.signature.purpose, 90))}</text>
    ${stepNodes}
    <text x="40" y="300" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Mnemos Journey View</text>
  `);
}

function renderTerminalBuildCard(
  memory: MemoryModel,
  score: ReturnType<typeof computeMemoryScore>,
  aiReadiness: ReturnType<typeof computeAiReadiness>,
): string {
  const duration = (memory.stats.durationMs / 1000).toFixed(1);
  return svgWrap(800, 360, `
    <style>
      @keyframes blink { 0%,49% { opacity: 1; } 50%,100% { opacity: 0; } }
      @keyframes fade { from { opacity: 0; } to { opacity: 1; } }
      .l { animation: fade .5s ease-out both; }
      .c { animation: blink 1s step-end infinite; }
    </style>
    <rect width="800" height="360" rx="24" fill="#0a0a0b"/>
    <rect x="1" y="1" width="798" height="358" rx="23" stroke="#27272a" stroke-width="2"/>
    <circle cx="28" cy="36" r="7" fill="#ef4444"/><circle cx="52" cy="36" r="7" fill="#f59e0b"/><circle cx="76" cy="36" r="7" fill="#22c55e"/>
    <text x="400" y="40" text-anchor="middle" font-family="system-ui,sans-serif" font-size="13" fill="#71717a">mnemos build</text>
    <text class="l" x="40" y="88" font-family="ui-monospace,monospace" font-size="15" fill="#a1a1aa">$ npx mnemos .</text>
    <text class="l" x="40" y="124" font-family="ui-monospace,monospace" font-size="14" fill="#818cf8">→ ${memory.stats.filesScanned.toLocaleString()} files · ${memory.stats.nodesCreated.toLocaleString()} nodes</text>
    <text class="l" x="40" y="160" font-family="ui-monospace,monospace" font-size="14" fill="#22c55e">✓ ${memory.domains.length} domains · ${memory.flows.length} flows · ${(memory.capabilities ?? []).length} capabilities</text>
    <text class="l" x="40" y="196" font-family="ui-monospace,monospace" font-size="14" fill="#22c55e">✓ project.dna.json · agent_context.json · snapshots/</text>
    <text class="l" x="40" y="232" font-family="ui-monospace,monospace" font-size="14" fill="#c8f542">Done in ${duration}s · health ${score.overall} · AI ${aiReadiness.score}</text>
    <rect x="40" y="268" width="720" height="10" rx="5" fill="#27272a"/>
    <rect x="40" y="268" width="${Math.min(720, Math.round((aiReadiness.score / 100) * 720))}" height="10" rx="5" fill="#6366f1"/>
    <rect class="c" x="320" y="218" width="2" height="20" fill="#c8f542"/>
    <text x="40" y="320" font-family="system-ui,sans-serif" font-size="12" fill="#52525b">${esc(memory.repository)} · ${esc(memory.architecture.type)}</text>
  `);
}

function renderBenchmarkResultsCard(memory: MemoryModel): string {
  const aiScore = Math.round((memory.stats.filesScanned > 0 ? 80 : 0));
  const barW = Math.round((aiScore / 100) * 480);
  const readiness = aiScore > 0 ? `${Math.min(99, 60 + memory.domains.length)}%` : '—';
  return svgWrap(800, 320, `
    <defs><linearGradient id="resGrad" x1="0" y1="0" x2="1" y2="0"><stop stop-color="#6366f1"/><stop offset="1" stop-color="#c8f542"/></linearGradient></defs>
    <style>
      @keyframes grow { from { width: 0; } to { width: ${barW}px; } }
      .bar { animation: grow 1.6s ease-out .4s forwards; width: 0; }
    </style>
    <rect width="800" height="320" rx="24" fill="#fbfbfd"/>
    <rect x="1" y="1" width="798" height="318" rx="23" stroke="#e8e8ed" stroke-width="2"/>
    <text x="40" y="48" font-family="system-ui,sans-serif" font-size="12" fill="#6366f1" font-weight="700" letter-spacing="1">REPOSITORY INTELLIGENCE</text>
    <text x="40" y="88" font-family="Georgia,serif" font-size="30" fill="#1d1d1f" font-weight="600">${esc(memory.repository)}</text>
    <text x="40" y="130" font-family="system-ui,sans-serif" font-size="14" fill="#515154">Structured memory beats raw repo dumps for AI task accuracy</text>
    <text x="40" y="180" font-family="system-ui,sans-serif" font-size="13" fill="#374151" font-weight="600">AI readiness</text>
    <rect x="200" y="166" width="480" height="22" rx="6" fill="#f3f4f6"/>
    <rect class="bar" x="200" y="166" height="22" rx="6" fill="url(#resGrad)"/>
    <text x="700" y="182" font-family="system-ui,sans-serif" font-size="14" fill="#6366f1" font-weight="700">${readiness}</text>
    <text x="40" y="230" font-family="system-ui,sans-serif" font-size="13" fill="#6b7280">${memory.stats.filesScanned.toLocaleString()} files → DNA fits in ~${Math.max(4, Math.round(memory.stats.filesScanned / 30)).toLocaleString()}K tokens</text>
    <text x="40" y="260" font-family="system-ui,sans-serif" font-size="13" fill="#6b7280">${memory.domains.length} domains · ${memory.flows.length} flows · share this SVG in README</text>
    <text x="40" y="300" font-family="system-ui,sans-serif" font-size="12" fill="#86868b">Mnemos · Anything Graphify shows as a graph, Mnemos shows here + answers questions</text>
  `);
}

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  return value.slice(0, max - 1) + '…';
}
